### ISSUE TITLE
Meta file missing

### ISSUE THREAD

**Issue by qingqhua** [SuikaSibyl/SIByLEngine2022#2]
Hi, I'm having trouble running the demo on Windows with Visual Studio 2022. 

The error log shows that some meta files are missing. Any idea what might be causing this issue? It would be great if a stable version is coming out.

![Untitled](https://github.com/user-attachments/assets/d815761a-6fc6-4247-b6a0-bb9a79ace4b9)

**Comment by SuikaSibyl** [comment]
Hi qingqing, I have read your work before! 

I updated some fixes for the issue today, and you can find more details in the "Compilation Instruction" section in README.md.

I am surprised you have fixed all the other issues to compile it :> Very sorry for the inconvenience...

**Comment by qingqhua** [comment]
Thanks! The test scene works for me now!
